### PR TITLE
Rename App to Application to support building on OS X. Minor updates …

### PR DESCRIPTION
**Pull request by srt4**
…to README.md to fix copy command and provide DB initialization instructions

I'm not sure why the `App.jsx` and `App` naming doesn't work on the Mac environments I've tried, but it seems like an incompatibility which renaming the component solves. The change is minor and non-functional.

### CODE REVIEW

**Comment by srt4** [comment]
I'm hesitant to open this up as a PR because it seems like a Mac-specific bug, but it's a small change and it may help others.

**Review by anstosa — APPROVED** [review]
Thanks!

**Comment by mileserickson** [comment]
Hey folks!

Somehow there's a revert commit in there and merging this PR ended up making no changes.

**Comment by srt4** [comment]
> Hey folks!
> 
> Somehow there's a revert commit in there and merging this PR ended up making no changes.

Good catch. I had pushed that change to my fork's master, forgetting that it would affect the scope of this PR. Opened https://github.com/anstosa/ferry.fyi/pull/27

**Comment by anstosa** [comment]
Wow thanks for the eagle-eye @mileserickson. Glad someone's paying attention 😂

**Pull request merged**
